accent = "#ff8852" # "#637867" 
cursor = "#e7e9ea"
foreground = "#e7e9ea"
background = "#000000" # "#2d353b"
selection_foreground = "#000000"
selection_background = "#e7e9ea"

color0 = "#121212"
color1 = "#8a8a8a"
color2 = "#e7e9ea" # Omarchy Logo, pdf
color3 = "#9e9e9e"
color4 = "#626262"
color5 = "#8a8a8a"
color6 = "#767676"
color7 = "#e0e0e0"
color8 = "#8a8a8a"
color9 = "#9e9e9e"
color10 = "#767676"
color11 = "#b2b2b2"
color12 = "#626262"
color13 = "#8a8a8a"
color14 = "#9e9e9e"
color15 = "#e7e9ea"
