## name : Felix

foreground #e7e9ea
background #000000

cursor #f59e0b

selection_foreground #EAEAEA
selection_background #f59e0b

active_tab_foreground #EAEAEA
active_tab_background #f59e0b
inactive_tab_foreground #333333

color0 #000000
color1 #e7e9ea
color2 #e7e9ea
color3 #e7e9ea
color4 #e7e9ea
color5 #e7e9ea
color6 #e7e9ea
color7 #e7e9ea
color8 #000000
color9 #e7e9ea
color10 #e7e9ea
color11 #e7e9ea
color12 #e7e9ea
color13 #e7e9ea
color14 #e7e9ea
color15 #e7e9ea
