# Use Felix color7 for active tmux elements.
set -g pane-active-border-style "fg=colour7"
set -g status-left "#[fg=colour0,bg=colour7,bold] #S #[bg=default] "
set -g window-status-current-format "#[fg=colour7,bold] #I:#W "
